# Generated by Django 3.1.2 on 2023-11-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name_plural': '3.Chuyến bay'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name_plural': '4.Hành khách'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': '1.Địa chỉ'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': '5.Vé '},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '6.Người dùng '},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name_plural': '2.Tuần'},
        ),
    ]
